# This workflow will pack your extension as a CRX file and upload it as an artifact
name: Pack Extension

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  # This job will run on ubuntu-latest
  pack:
    runs-on: ubuntu-latest

    steps:
  - id: packExtensionDir
    uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
    with:
      extensionDir: 'extension'
      zipFilePath: 'build/extension.zip'
  - uses: cardinalby/webext-buildtools-chrome-crx-action@v2
    with:
      # zip file made at the packExtensionDir step
      zipFilePath: 'build/extension.zip'
      crxFilePath: 'build/extension.crx'
      privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}

      # Upload the CRX file as an artifact
      - name: Upload the CRX file as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension.crx
          path: build/extension.crx
